CREATE DATABASE AliNinoDB
CREATE TABLE Categories
(
ID INT IDENTITY PRIMARY KEY,
TITLE NVARCHAR(500),
ParentCategoryId INT 
)
INSERT INTO Categories(TITLE,ParentCategoryId)
VALUES(N'HI',1)
SELECT*FROM Categories




CREATE TABLE BOOKS
(
ID INT IDENTITY,
TITLE NVARCHAR(500),
DESCRIPTION NVARCHAR(500),
ActualPrice INT,
DiscountPrice INT
)
INSERT INTO BOOKS(TITLE,DESCRIPTION,ActualPrice,DiscountPrice)
VALUES(N'KITAB',N'GELISIM',200,39)
SELECT*FROM BOOKS



CREATE TABLE Authors
(
ID INT IDENTITY,
NAME NVARCHAR(20),
SURNAME NVARCHAR(20)
)
INSERT INTO Authors(NAME,SURNAME)
VALUES(N'QEMER',N'UMBYVA')
SELECT*FROM Authors



CREATE TABLE Bookauthors
(
ID INT IDENTITY,
BOOK_ID INT ,
AUTHOR_ID INT  
)
INSERT INTO Bookauthors(BOOK_ID,AUTHOR_ID)
VALUES(5,6)
SELECT*FROM Bookauthors




CREATE TABLE PublishingHouses
(
ID INT IDENTITY,
TITLE NVARCHAR(500)
)
INSERT INTO PublishingHouses(TITLE)
VALUES(N'title')
SELECT*FROM PublishingHouses




CREATE TABLE BooksGenres
(
ID INT IDENTITY,
BOOK_ID INT IDENTITY,
GENRE_ID INT IDENTITY
)
INSERT INTO BooksGenres(BOOK_ID,GENRE_ID)
VALUES(5,7)
SELECT*FROM BooksGenres




CREATE TABLE Genres
(
ID INT IDENTITY,
TITLE NVARCHAR(500),
IS_DELETED BIT
)
INSERT INTO Genres(TITLE,IS_DELETED)
VALUES(N'BEDII',NULL)
SELECT*FROM Genres


CREATE TABLE Bindings
(
ID INT IDENTITY,
TITLE NVARCHAR(500),
IS_DELETED BIT
)
INSERT INTO Bindings(TITLE,IS_DELETED)
VALUES(N'TITLEE',NULL)
SELECT*FROM Bindings


CREATE TABLE Languages
(
ID INT IDENTITY,
TITLE NVARCHAR(500),
IS_DELETED BIT
)
INSERT INTO Languages(TITLE,IS_DELETED)
VALUES(N'TITLEEE',NULL)
SELECT*FROM Languages



CREATE TABLE Bookslanguages
(
ID INT IDENTITY,
BOOK_ID INT,
LANGUAGE_ID INT
)
INSERT INTO Bookslanguages(BOOK_ID,LANGUAGE_ID)
VALUES(5,9)
SELECT*FROM Bookslanguages




CREATE TABLE Comments
(
ID INT IDENTITY,
DESCRIPTION NVARCHAR(500),
BOOK_ID INT,
RATING ,
NAME NVARCHAR(50),
EMAIL NVARCHAR(50)

)
INSERT INTO Comments(DESCRIPTION ,BOOK_ID,RATING,NAME,EMAIL)
VALUES(N'TITLE',5,4,N'ALYA',N'ALYAGAGS@GMAIL.COM')
SELECT*FROM Comments



